In [3]:
import torch

In [7]:
def linear_q_with_scale_and_zero_point(tensor,scale,zero_point,dtype=torch.int8):
    scale_and_shift_tensor = tensor /scale +zero_point
    rounded_tensor = torch.round(scale_and_shift_tensor)
    q_min = torch.iinfo(dtype).min
    q_max = torch.iinfo(dtype).max
    q_tensor = rounded_tensor.clamp(q_min,q_max).to(dtype)
    return q_tensor


In [13]:
test_tensor = torch.tensor(
    [[191.6,-13.5,728.6],
     [92.14,295.5, -184],
     [0,    684.6,245.5]]
)
zero_point = -70
scale = 3.5
quantized_tensor = linear_q_with_scale_and_zero_point(test_tensor,scale,zero_point)

In [14]:
quantized_tensor

tensor([[ -15,  -74,  127],
        [ -44,   14, -123],
        [ -70,  126,    0]], dtype=torch.int8)

In [ ]:
dequantized_tensor = scale*(quantized_tensor-zero_point)#错误的方法 quantized_tensor没有转换成浮点数，会出现溢出问题

In [16]:
dequantized_tensor

tensor([[ 192.5000,  -14.0000, -206.5000],
        [  91.0000,  294.0000, -185.5000],
        [   0.0000, -210.0000,  245.0000]])

In [17]:
dequantized_tensor = scale*(quantized_tensor.float()-zero_point)
dequantized_tensor

tensor([[ 192.5000,  -14.0000,  689.5000],
        [  91.0000,  294.0000, -185.5000],
        [   0.0000,  686.0000,  245.0000]])